language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install ./IdP"
# command to run tests
script: pytest IdP

branches:
  only:
    - master

notifications:
    email: false
